### ISSUE TITLE
Cannot insert date

### ISSUE THREAD

**Issue by piglovesyou** [matehat/cqex#21]
When I try to insert date value, it fails.
```
** (Protocol.UndefinedError) protocol Enumerable not implemented for ~D[1959-12-22]
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:116: Enumerable.reduce/3
    (elixir) lib/enum.ex:1767: Enum.map/2
    (cqex) lib/cqex/query.ex:139: CQEx.Query.nullify/2
    (cqex) lib/cqex/query.ex:141: anonymous fn/2 in CQEx.Query.nullify/2
    (elixir) lib/enum.ex:1233: anonymous fn/3 in Enum.map/2
    (stdlib) lists.erl:1263: :lists.foldl/3
    (elixir) lib/enum.ex:1772: Enum.map/2
```

DESCRIBE table result:
```
cqlsh:lazzarone_dev> DESCRIBE users ;

CREATE TABLE lazzarone_dev.users (
    birthday date,
    id int,
    PRIMARY KEY (birthday, id)
) ...
```

**Comment by pragmatist-nz** [comment]
I came across this as well, you need to convert the date object into its erlang representation, i.e.:

    %{ changes | your_date_field: Date.to_erl(your_date_field)}

**Comment by piglovesyou** [comment]
I see.. Thank you!
